<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Arabic' => 'Arab',
    'CSV' => 'CSV',
    'Configure Order and Display of Grid Columns' => 'Mengkonfigurasi Perintah dan Paparan Lajur Grid',
    'Delete' => 'Padam',
    'English' => 'Bahasa Inggeris',
    'Error {code}' => 'Ralat {code}',
    'Excel' => 'Excel',
    'Integer between {min} to {max}' => 'Integer antara {min} hingga {max}',
    'Malayalam' => 'Malayalam',
    'Personalize Grid Configuration' => 'Peribadikan Konfigurasi Grid',
    'Preview' => 'Pratonton',
    'Save' => 'Simpan',
    'Select a filter...' => 'Pilih penapis ...',
    'Select a sort...' => 'Pilih sejenis ...',
    'Select a theme...' => 'Pilih tema ...',
    'Select theme to style grid' => 'Pilih tema ke grid gaya',
    'Select...' => 'Pilih ...',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => 'Tetapkan nama untuk menyimpan keadaan {category} grid semasa anda. Anda boleh memilih {category} disimpan alternatif dari senarai di bawah untuk mengedit atau memadam. ',
    'Set default grid filter criteria' => 'Tetapkan kriteria penapis grid piawai',
    'Set default grid sort criteria' => 'Tetapkan kriteria semak grid lalai',
    'Text' => 'Teks',
    'rows per page' => 'baris setiap halaman',
];