<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Arabic' => '',
    'CSV' => '',
    'Configure Order and Display of Grid Columns' => '',
    'Delete' => '',
    'English' => '',
    'Error {code}' => '',
    'Excel' => '',
    'Integer between {min} to {max}' => '',
    'Malayalam' => '',
    'Personalize Grid Configuration' => '',
    'Preview' => '',
    'Save' => '',
    'Select a filter...' => '',
    'Select a sort...' => '',
    'Select a theme...' => '',
    'Select theme to style grid' => '',
    'Select...' => '',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => '',
    'Set default grid filter criteria' => '',
    'Set default grid sort criteria' => '',
    'Text' => '',
    'rows per page' => '',
];
