<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Arabic' => 'Arab',
    'CSV' => 'CSV',
    'Configure Order and Display of Grid Columns' => 'Konfigurasi Urutan dan Tampilan Kolom Grid',
    'Delete' => 'Hapus',
    'English' => 'Bahasa Inggris',
    'Error {code}' => 'Kesalahan {code}',
    'Excel' => 'Excel',
    'Integer between {min} to {max}' => 'Bilangan bulat antara {min} hingga {max}',
    'Malayalam' => 'Malayalam',
    'Personalize Grid Configuration' => 'Personalisasi Grid Konfigurasi',
    'Preview' => 'Pratinjau',
    'Save' => 'Simpan',
    'Select a filter...' => 'Pilih menyaring ...',
    'Select a sort...' => 'Pilih semacam ...',
    'Select a theme...' => 'Pilih tema ...',
    'Select theme to style grid' => 'Pilih tema ke grid gaya',
    'Select...' => 'Pilih ...',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => 'Setel nama untuk menyimpan keadaan kisi Anda saat ini {category}. Anda dapat memilih salah satu dari {category} yang tersimpan dari daftar di bawah ini untuk diedit atau dihapus. ',
    'Set default grid filter criteria' => 'Set kriteria filter grid default',
    'Set default grid sort criteria' => 'Tentukan kriteria jenis grid default',
    'Text' => 'Teks',
    'rows per page' => 'baris per halaman',
];